package com.opayque.api.wallet.service;

import com.opayque.api.integration.currency.CurrencyExchangeService;
import com.opayque.api.wallet.dto.CreateLedgerEntryRequest;
import com.opayque.api.wallet.entity.Account;
import com.opayque.api.wallet.entity.LedgerEntry;
import com.opayque.api.wallet.entity.TransactionType;
import com.opayque.api.wallet.repository.AccountRepository;
import com.opayque.api.wallet.repository.LedgerRepository;
import net.jqwik.api.*;
import net.jqwik.api.lifecycle.BeforeTry;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.data.repository.query.FluentQuery;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.*;
import java.util.function.Function;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

/// **The "Math" Layer — Property-Based Testing (PBT) for Financial Invariants**.
///
/// This test suite utilizes **jqwik** to perform high-density property-based testing on the
/// core mathematical logic of the ledger. Unlike standard unit tests, this suite generates hundreds
/// of random transaction scenarios to verify that the ledger's invariants hold true under all
/// edge cases.
///
/// **Tested Invariants:**
/// * **Balance Consistency:** The sum of all credits minus debits must always equal the current balance.
/// * **Conversion Integrity:** Applied exchange rates must result in exact amounts using **Bankers' Rounding**.
///
@SuppressWarnings({
        "NullableProblems",
                "unchecked",
                "FieldCanBeLocal",
                "DataFlowIssue",
                "Lombok"
                })
class LedgerPropertyTest {

    private LedgerService ledgerService;
    private FakeLedgerRepository fakeRepository;
    private AccountRepository accountRepository;
    private CurrencyExchangeService exchangeService;

    private final UUID accountId = UUID.randomUUID();

    /// Fixed account instance used to stabilize testing of currency conversion logic.
    private final Account eurAccount = Account.builder()
            .id(accountId)
            .currencyCode("EUR")
            .iban("DE00123456789012345678")
            .build();

    /// Orchestrates the mock environment before every property "try".
    ///
    /// This setup ensures:
    /// 1. A clean [FakeLedgerRepository] to prevent state leakage between property runs.
    /// 2. Dynamic [Account] resolution to handle randomized UUIDs generated by jqwik.
    /// 3. Deterministic exchange rates for repeatable mathematical verification.
    @BeforeTry
    @SuppressWarnings("unused")
    void setUp() {
        accountRepository = mock(AccountRepository.class);
        exchangeService = mock(CurrencyExchangeService.class);
        fakeRepository = new FakeLedgerRepository();

        when(accountRepository.findByIdForUpdate(any(UUID.class))).thenAnswer(invocation -> {
            UUID requestedId = invocation.getArgument(0);
            return Optional.of(Account.builder()
                    .id(requestedId)
                    .currencyCode("EUR")
                    .iban("DE" + requestedId.toString().substring(0, 15))
                    .build());
        });

        when(exchangeService.getRate(anyString(), anyString())).thenAnswer(invocation -> {
            String from = invocation.getArgument(0);
            if (from.equals("USD")) return new BigDecimal("0.850000");
            if (from.equals("GBP")) return new BigDecimal("1.150000");
            return BigDecimal.ONE;
        });

        ledgerService = new LedgerService(fakeRepository, accountRepository, exchangeService);
    }

    /// **Property 1: Ledger Balance Invariant**.
    ///
    /// Verifies that for any list of valid transactions, the aggregate sum matches the
    /// calculated balance exactly, accounting for multi-currency conversions and
    /// **HALF_EVEN** rounding.
    ///
    /// @param accountId Randomized account identifier provided by `validUuids`.
    /// @param transactions Randomized list of ledger requests provided by `validEntries`.
    @Property(tries = 100)
    void invariant_balance_sum(
            @ForAll("validUuids") UUID accountId,
            @ForAll List<@From("validEntries") CreateLedgerEntryRequest> transactions
    ) {
        BigDecimal expectedBalance = BigDecimal.ZERO;

        for (CreateLedgerEntryRequest request : transactions) {
            CreateLedgerEntryRequest fixedRequest = new CreateLedgerEntryRequest(
                    accountId,
                    request.amount(),
                    request.currency(),
                    request.type(),
                    request.description(),
                    request.timestamp()
            );

            ledgerService.recordEntry(fixedRequest);

            BigDecimal effectiveAmount = fixedRequest.amount();

            if (!fixedRequest.currency().equals("EUR")) {
                BigDecimal rate = BigDecimal.ONE;
                if (fixedRequest.currency().equals("USD")) rate = new BigDecimal("0.850000");
                if (fixedRequest.currency().equals("GBP")) rate = new BigDecimal("1.150000");

                // Logic replication: Rate application followed by Bankers' Rounding (HALF_EVEN)
                effectiveAmount = effectiveAmount.multiply(rate).setScale(2, RoundingMode.HALF_EVEN);
            }

            if (fixedRequest.type() == TransactionType.CREDIT) {
                expectedBalance = expectedBalance.add(effectiveAmount);
            } else {
                expectedBalance = expectedBalance.subtract(effectiveAmount);
            }
        }

        BigDecimal actualBalance = ledgerService.calculateBalance(accountId);

        assertThat(actualBalance)
                .as("Invariant Violation: Ledger Balance mismatch")
                .isEqualByComparingTo(expectedBalance);
    }

    /// **Property 2: Conversion Integrity Invariant**.
    ///
    /// Validates that the conversion from an original currency to the account's base currency
    /// is recorded with sub-cent precision and correctly persisted in the [LedgerEntry].
    ///
    /// @param originalAmount Randomized financial value.
    /// @param currency Randomized source currency (USD, EUR, GBP).
    @Property(tries = 500)
    void invariant_conversion_integrity(
            @ForAll("validAmounts") BigDecimal originalAmount,
            @ForAll("validCurrencies") String currency) {

        CreateLedgerEntryRequest request = new CreateLedgerEntryRequest(
                accountId, originalAmount, currency, TransactionType.CREDIT, "PBT Check", null
        );

        LedgerEntry entry = ledgerService.recordEntry(request);

        BigDecimal rate = entry.getExchangeRate();
        BigDecimal expectedStoredAmount = originalAmount.multiply(rate).setScale(2, RoundingMode.HALF_EVEN);

        assertThat(entry.getAmount()).isEqualByComparingTo(expectedStoredAmount);
    }

    // --- DATA GENERATORS (ARBITRARIES) ---

    /// Generates a randomized list of transaction requests for bulk stress testing.
    @Provide
    @SuppressWarnings("unused")
    Arbitrary<List<CreateLedgerEntryRequest>> validTransactions() {
        return Arbitraries.forType(CreateLedgerEntryRequest.class)
                .list().ofMinSize(1).ofMaxSize(50);
    }

    /// Generates realistic bank-grade amounts between 1.00 and 1,000,000.00.
    @Provide
    @SuppressWarnings("unused")
    Arbitrary<BigDecimal> validAmounts() {
        return Arbitraries.bigDecimals().between(BigDecimal.ONE, new BigDecimal("1000000")).ofScale(2);
    }

    /// Limits generated currencies to the supported set (USD, EUR, GBP).
    @Provide
    @SuppressWarnings("unused")
    Arbitrary<String> validCurrencies() {
        return Arbitraries.of("USD", "EUR", "GBP");
    }

    /// Provides randomized UUIDs to simulate high-cardinality account data.
    @Provide
    Arbitrary<UUID> validUuids() {
        return Arbitraries.randomValue(random -> UUID.randomUUID());
    }

    /// Composes a full [CreateLedgerEntryRequest] by combining multiple primitive generators.
    @Provide
    @SuppressWarnings("unused")
    Arbitrary<CreateLedgerEntryRequest> validEntries() {
        return Combinators.combine(
                validUuids(),
                validAmounts(),
                validCurrencies(),
                Arbitraries.of(TransactionType.class),
                Arbitraries.strings().alpha().ofLength(10),
                Arbitraries.of((java.time.LocalDateTime) null)
        ).as(CreateLedgerEntryRequest::new);
    }

    // --- FAKE REPOSITORY IMPLEMENTATION ---

    /// In-memory mock of the [LedgerRepository] to facilitate rapid PBT execution.
    ///
    /// This implementation bypasses the database to focus purely on the mathematical
    /// invariants of the service layer while maintaining Spring Data interface compatibility.
    static class FakeLedgerRepository implements LedgerRepository {
        private final List<LedgerEntry> store = new ArrayList<>();

        @Override
        public LedgerEntry save(LedgerEntry entity) {
            if (entity.getId() == null) entity.setId(UUID.randomUUID());
            store.add(entity);
            return entity;
        }

        /// Aggregates balance from the in-memory store using the same CREDIT/DEBIT logic as the production DB.
        public BigDecimal getBalance(UUID accountId) {
            return store.stream()
                    .map(e -> e.getTransactionType() == TransactionType.CREDIT ? e.getAmount() : e.getAmount().negate())
                    .reduce(BigDecimal.ZERO, BigDecimal::add);
        }

        public List<LedgerEntry> getAllEntries() { return new ArrayList<>(store); }

        // --- Safe Stubs to satisfy Interface constraints and Non-Null APIs ---

        @Override public List<LedgerEntry> findAll() { return Collections.emptyList(); }
        @Override public List<LedgerEntry> findAll(Sort sort) { return Collections.emptyList(); }
        @Override public Page<LedgerEntry> findAll(Pageable pageable) { return Page.empty(); }
        @Override public List<LedgerEntry> findAllById(Iterable<UUID> uuids) { return Collections.emptyList(); }
        @Override public <S extends LedgerEntry> List<S> saveAll(Iterable<S> entities) { return Collections.emptyList(); }
        @Override public void flush() {}
        @Override public <S extends LedgerEntry> S saveAndFlush(S entity) { return entity; }
        @Override public <S extends LedgerEntry> List<S> saveAllAndFlush(Iterable<S> entities) { return Collections.emptyList(); }
        @Override public void deleteAllInBatch(Iterable<LedgerEntry> entities) {}
        @Override public void deleteAllByIdInBatch(Iterable<UUID> uuids) {}
        @Override public void deleteAllInBatch() {}
        @Override public LedgerEntry getOne(UUID uuid) { throw new UnsupportedOperationException(); }
        @Override public LedgerEntry getReferenceById(UUID uuid) { throw new UnsupportedOperationException(); }
        @Override public LedgerEntry getById(UUID uuid) { throw new UnsupportedOperationException(); }
        @Override public <S extends LedgerEntry> Optional<S> findOne(Example<S> example) { return Optional.empty(); }
        @Override public <S extends LedgerEntry> List<S> findAll(Example<S> example) { return Collections.emptyList(); }
        @Override public <S extends LedgerEntry> List<S> findAll(Example<S> example, Sort sort) { return Collections.emptyList(); }
        @Override public <S extends LedgerEntry> Page<S> findAll(Example<S> example, Pageable pageable) { return Page.empty(); }
        @Override public <S extends LedgerEntry> long count(Example<S> example) { return 0; }
        @Override public <S extends LedgerEntry> boolean exists(Example<S> example) { return false; }
        @Override public <S extends LedgerEntry, R> R findBy(Example<S> example, Function<FluentQuery.FetchableFluentQuery<S>, R> queryFunction) { return null; }
        @Override public Optional<LedgerEntry> findById(UUID uuid) { return Optional.empty(); }
        @Override public boolean existsById(UUID uuid) { return false; }
        @Override public long count() { return 0; }
        @Override public void deleteById(UUID uuid) {}
        @Override public void delete(LedgerEntry entity) {}
        @Override public void deleteAllById(Iterable<? extends UUID> uuids) {}
        @Override public void deleteAll(Iterable<? extends LedgerEntry> entities) {}
        @Override public void deleteAll() {}
    }
}