package com.opayque.api.card.service;

import com.opayque.api.card.controller.CardController;
import com.opayque.api.infrastructure.exception.CardLimitExceededException;
import net.jqwik.api.*;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.data.redis.core.ValueOperations;
import org.springframework.data.redis.serializer.RedisSerializer;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.UUID;

import static org.assertj.core.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

/**
 * <p>
 * {@code CardLimitServicePropertyTest} provides a comprehensive set of
 * property‑based tests that verify the functional contract of
 * {@link CardLimitService}. The tests are written using JUnit 5, the
 * {@code jqwik} property testing framework, and Mockito for isolating the
 * Redis interactions.
 * </p>
 *
 * <p>
 * The primary purpose of this test suite is to ensure that the spend‑limit
 * validation logic behaves correctly under a wide range of inputs, including
 * edge cases that are difficult to capture with conventional example‑based
 * tests. Each {@code @Property} method encodes a mathematical invariant or a
 * business rule that must hold for every generated argument set.
 * </p>
 *
 * <p><b>Key invariants covered</b></p>
 * <ul>
 *   <li>
 *     <b>Unlimited Card Invariant</b> – When the limit is {@code null},
 *     {@link CardLimitService#checkSpendLimit(UUID, BigDecimal, BigDecimal)}
 *     must never invoke the Lua script and must allow any amount.
 *   </li>
 *   <li>
 *     <b>Safe Spend Mathematics</b> – If the Redis Lua script returns {@code 1L}
 *     (success), the spend check must complete without throwing.
 *   </li>
 *   <li>
 *     <b>Hard Stop Mathematics</b> – If the Lua script returns {@code -1L}
 *     (breach), the check must throw {@link CardLimitExceededException}.
 *   </li>
 *   <li>
 *     <b>Precision Trap</b> – High‑precision monetary values are passed to the
 *     Lua script as {@code String}s to avoid JSON double‑precision loss.
 *   </li>
 *   <li>
 *     <b>No‑Op Record Spend</b> – The {@code recordSpend} method performs no
 *     Redis interaction; all state changes are handled atomically in the check.
 *   </li>
 *   <li>
 *     <b>Rollback Key Determinism</b> – The rollback operation uses a
 *     deterministic key format {@code "spend:{uuid}:{yyyy-MM}"} to ensure
 *     correct monthly aggregation.
 *   </li>
 * </ul>
 *
 * <p>
 * The test class defines a private {@code record TestContext} that bundles a
 * fresh {@link CardLimitService} instance with a mocked
 * {@link RedisTemplate RedisTemplate}. This
 * context is re‑created for each property execution to guarantee isolation.
 * </p>
 *
 * @author Madavan Babu
 * @since 2026
 *
 * @see CardLimitService
 * @see CardController
 * @see com.opayque.api.card.repository.VirtualCardRepository
 */
@ExtendWith(MockitoExtension.class)
@SuppressWarnings("unchecked, unused")
class CardLimitServicePropertyTest {

    // Helper to setup Mocks cleanly for every property run
    private record TestContext(
            CardLimitService service,
            RedisTemplate<String, Object> redisTemplate
            // ValueOperations removed as it's no longer used for the main check logic
    ) {}

    private TestContext setup() {
        // 1. Change generics to <String, Object> to match the Service's requirement
        @SuppressWarnings("unchecked")
        RedisTemplate<String, Object> redisTemplate = mock(RedisTemplate.class);

        // 2. Stub the serializer to avoid NPEs when service calls getStringSerializer()
        lenient().when(redisTemplate.getStringSerializer()).thenReturn(RedisSerializer.string());

        // 3. Return the context
        return new TestContext(new CardLimitService(redisTemplate), redisTemplate);
    }

    // =========================================================================
    // PROPERTY 1: The "Unlimited Card" Invariant
    // =========================================================================

    /**
     * Verifies that a card with an unlimited spending limit (i.e., {@code monthlyLimit == null})
     * permits any transaction amount without invoking the Lua script that performs the limit check.
     *
     * <p>The purpose of this property‑based test is to ensure that the short‑circuit logic in
     * {@link CardLimitService#checkSpendLimit(UUID, BigDecimal, BigDecimal)} correctly bypasses
     * Redis/Lua processing when the limit is {@code null}, thereby improving performance for
     * unlimited cards.</p>
     *
     * @param cardId the identifier of the virtual card under test; generated by the
     *               {@code @ForAll("validCardId")} provider.
     * @param amount a randomly generated {@link BigDecimal} representing a
     *               potentially very large spend amount; supplied by the
     *               {@code @ForAll("hugeAmounts")} provider.
     *
     *
     * @see CardLimitService
     * @see CardLimitServicePropertyTest
     * @see RedisTemplate
     */
    @Property
    @Label("1. Unlimited cards (limit=null) should allow ANY amount (Skip Lua)")
    void unlimitedCardsShouldAllowAnyAmount(
            @ForAll("validCardId") UUID cardId,
            @ForAll("hugeAmounts") BigDecimal amount
    ) {
        TestContext ctx = setup();

        // Act
        assertThatCode(() -> ctx.service.checkSpendLimit(cardId, null, amount))
                .doesNotThrowAnyException();

        // Assert: Verify Lua script was NEVER executed (Logic short-circuits)
        verify(ctx.redisTemplate, never()).execute(any(), any(), any(), anyList(), any());
    }

    // =========================================================================
    // PROPERTY 2: The "Safe Spend" Mathematics
    // =========================================================================
    /**
     * Ensures that a transaction whose amount is within the configured limit always passes
     * when the Lua script executed via Redis returns {@code 1L} (success).
     *
     * <p>This property‑based test validates the contract of
     * {@link CardLimitService#checkSpendLimit(UUID, BigDecimal, BigDecimal)}:
     * a successful Lua evaluation must be interpreted as a non‑exceptional spend,
     * guaranteeing that legitimate purchases are not blocked.</p>
     *
     * @param cardId the identifier of the virtual card under test; supplied by the
     *               {@code @ForAll("validCardId")} provider.
     * @param limit  the spend limit to be applied for the test case; generated by the
     *               {@code @ForAll("financialAmounts")} provider.
     * @param amount the transaction amount to verify against the {@code limit};
     *               also produced by the {@code @ForAll("financialAmounts")} provider.
     *
     * @see CardLimitService
     * @see CardLimitServicePropertyTest
     * @see RedisTemplate
     *
     */
    @Property
    @Label("2. Transactions where Lua returns Success (1L) must ALWAYS pass")
    void transactionsWithinLimitShouldAlwaysPass(
            @ForAll("validCardId") UUID cardId,
            @ForAll("financialAmounts") BigDecimal limit,
            @ForAll("financialAmounts") BigDecimal amount
    ) {
        TestContext ctx = setup();

        // FIX: Mock the Lua script returning 1L (Success)
        lenient().when(ctx.redisTemplate.execute(
                        any(org.springframework.data.redis.core.script.RedisScript.class),
                        any(org.springframework.data.redis.serializer.RedisSerializer.class),
                        any(org.springframework.data.redis.serializer.RedisSerializer.class),
                        anyList(),
                        any(), any(), any()))
                .thenReturn(1L);

        // Act & Assert
        assertThatCode(() -> ctx.service.checkSpendLimit(cardId, limit, amount))
                .doesNotThrowAnyException();
    }

    // =========================================================================
    // PROPERTY 3: The "Hard Stop" Mathematics
    // =========================================================================

    /**
     * Verifies that a transaction whose amount exceeds the configured spend limit always results
     * in a {@link CardLimitExceededException} when the underlying Lua script executed via Redis
     * returns a breach indicator ({@code -1L}).
     *
     * <p>This property‑based test enforces the core business rule of the
     * {@link CardLimitService#checkSpendLimit(UUID, BigDecimal, BigDecimal)} method:
     * any spend that is identified as a breach by the Lua evaluation must be rejected
     * immediately, preserving the integrity of the card‑level limit enforcement.</p>
     *
     * @param cardId the identifier of the virtual card under test; supplied by the
     *               {@code @ForAll("validCardId")} provider. {@link UUID}
     * @param limit  the spend limit configured for the card; generated by the
     *               {@code @ForAll("financialAmounts")} provider. {@link BigDecimal}
     * @param amount the transaction amount to be evaluated against {@code limit};
     *               also produced by the {@code @ForAll("financialAmounts")} provider.
     *               {@link BigDecimal}
     *
     *
     * @see CardLimitService
     * @see CardLimitServicePropertyTest
     * @see RedisTemplate
     * @see CardController
     * @see com.opayque.api.card.repository.VirtualCardRepository
     */
    @Property
    @Label("3. Transactions where Lua returns Breach (-1L) must ALWAYS throw")
    void transactionsExceedingLimitShouldAlwaysThrow(
            @ForAll("validCardId") UUID cardId,
            @ForAll("financialAmounts") BigDecimal limit,
            @ForAll("financialAmounts") BigDecimal amount
    ) {
        TestContext ctx = setup();

        // FIX: Mock the Lua script returning -1L (Breach)
        lenient().when(ctx.redisTemplate.execute(
                        any(org.springframework.data.redis.core.script.RedisScript.class),
                        any(org.springframework.data.redis.serializer.RedisSerializer.class),
                        any(org.springframework.data.redis.serializer.RedisSerializer.class),
                        anyList(),
                        any(), any(), any()))
                .thenReturn(-1L);

        // Act & Assert
        assertThatThrownBy(() -> ctx.service.checkSpendLimit(cardId, limit, amount))
                .isInstanceOf(CardLimitExceededException.class);
    }

    // =========================================================================
    // PROPERTY 4: The "Precision Trap" (Correct String Argument Passing)
    // =========================================================================

    /**
     * Verifies that high‑precision transaction amounts are passed to the Lua script
     * invoked via {@link RedisTemplate} as {@link String} values, avoiding precision loss
     * caused by JSON serialization of {@link BigDecimal}.
     *
     * <p>The test configures a lenient mock of {@link RedisTemplate}, calls
     * {@link CardLimitService#checkSpendLimit(UUID, BigDecimal, BigDecimal)} with a
     * high‑precision {@code amount}, and then captures the arguments supplied to
     * {@code RedisTemplate.execute(...)}. It asserts that both the spend {@code amount}
     * and the spend {@code limit} are supplied using {@code amount.toString()} and
     * {@code limit.toString()} respectively.</p>
     *
     * @param cardId the identifier of the virtual card under test; provided by the
     *               {@code @ForAll("validCardId")} generator.
     * @param amount a {@link BigDecimal} representing a high‑precision spend
     *               amount; generated by the {@code @ForAll("highPrecisionAmounts")} provider.
     *
     * @see CardLimitService
     * @see CardLimitServicePropertyTest
     * @see RedisTemplate
     * @see CardController
     */
    @Property
    @Label("4. High-precision amounts should be passed to Lua as Strings")
    void recordSpendShouldHandleHighPrecisionAmounts(
            @ForAll("validCardId") UUID cardId,
            @ForAll("highPrecisionAmounts") BigDecimal amount
    ) {
        TestContext ctx = setup();
        BigDecimal limit = new BigDecimal("10000.00");

        // Mock success so we can verify arguments
        lenient().when(ctx.redisTemplate.execute(
                        any(org.springframework.data.redis.core.script.RedisScript.class),
                        any(org.springframework.data.redis.serializer.RedisSerializer.class),
                        any(org.springframework.data.redis.serializer.RedisSerializer.class),
                        anyList(),
                        any(), any(), any()))
                .thenReturn(1L);

        ctx.service.checkSpendLimit(cardId, limit, amount);

        // Capture what was sent to Redis execute()
        // We expect the amount to be passed as a String to avoid JSON double precision issues
        verify(ctx.redisTemplate).execute(
                any(org.springframework.data.redis.core.script.RedisScript.class),
                any(org.springframework.data.redis.serializer.RedisSerializer.class),
                any(org.springframework.data.redis.serializer.RedisSerializer.class),
                anyList(),
                eq(amount.toString()), // CHECK 1: Amount passed as String
                eq(limit.toString()),  // CHECK 2: Limit passed as String
                anyString()
        );
    }

    // =========================================================================
    // PROPERTY 5: The "No-Op" Record Spend
    // =========================================================================

    /**
     * Verifies that {@link CardLimitService#recordSpend(UUID, BigDecimal)} is a no‑op
     * after the spend‑recording logic was moved to the atomic check phase.
     *
     * <p>The test creates a {@link TestContext} with mocked dependencies, invokes the
     * service method with a generated {@code cardId} and {@code amount}, and then
     * confirms that no interaction with {@link RedisTemplate} occurs. This ensures
     * that the method does not perform any Redis/Lua operations, avoiding unnecessary
     * I/O and preserving the performance benefits of the refactored design.</p>
     *
     * @param cardId the identifier of the virtual card under test; supplied by the
     *               {@code @ForAll("validCardId")} generator.
     * @param amount the transaction amount used for the call; supplied by the
     *               {@code @ForAll("financialAmounts")} generator.
     *
     * @see CardLimitService
     * @see CardLimitServicePropertyTest
     * @see RedisTemplate
     * @see CardController
     */
    @Property
    @Label("5. recordSpend should be a No-Op (Logic moved to Atomic Check)")
    void recordSpendShouldBeNoOp(
            @ForAll("validCardId") UUID cardId,
            @ForAll("financialAmounts") BigDecimal amount
    ) {
        TestContext ctx = setup();

        ctx.service.recordSpend(cardId, amount);

        // Verify NO interaction with Redis Template
        verifyNoInteractions(ctx.redisTemplate);
    }

    // =========================================================================
    // PROPERTY 6: Key Generation Determinism
    // =========================================================================

    /**
     * Verifies that the {@code rollbackSpend} operation generates a Redis key that follows the
     * required {@code "spend:{cardId}:{yyyy-MM}"} pattern.
     * <p>
     * The key format is critical for consistent aggregation and retrieval of spend data per card
     * and month in the Redis store. By enforcing this naming convention, the system can correctly
     * track rollbacks and ensure that the decrement operation targets the appropriate monthly bucket.
     * </p>
     *
     * @param cardId {@code UUID} identifying the card for which the spend is being rolled back.
     *               This identifier becomes the second segment of the Redis key.
     * @param amount {@code BigDecimal} amount to be rolled back. Although the amount itself is not
     *               part of the key, it is passed to {@link CardLimitService#rollbackSpend(UUID, BigDecimal)}
     *               to adjust the stored total.
     *
     * @see CardController
     * @see CardTransactionService
     * @see CardLimitService
     */
    @Property
    @Label("6. Rollback must use correct 'spend:uuid:yyyy-MM' key format")
    void rollbackShouldUseCorrectKeyFormat(
            @ForAll("validCardId") UUID cardId,
            @ForAll("financialAmounts") BigDecimal amount
    ) {
        TestContext ctx = setup();

        // Setup local ValueOperations mock just for rollback logic
        ValueOperations<String, Object> valueOps = mock(ValueOperations.class);
        when(ctx.redisTemplate.opsForValue()).thenReturn(valueOps);

        // Act: Rollback
        ctx.service.rollbackSpend(cardId, amount);

        ArgumentCaptor<String> keyCaptor = ArgumentCaptor.forClass(String.class);
        verify(valueOps).increment(keyCaptor.capture(), anyDouble());

        String key = keyCaptor.getValue();
        String currentMonth = LocalDate.now().format(DateTimeFormatter.ofPattern("yyyy-MM"));

        assertThat(key).startsWith("spend:" + cardId + ":" + currentMonth);
        assertThat(key).matches("spend:[a-f0-9\\-]+:\\d{4}-\\d{2}");
    }

    // =========================================================================
    // PROPERTY 7: Negative Amount Handling (Refunds/Rollbacks)
    // =========================================================================

    /**
     * <p>Ensures that {@link CardLimitService#rollbackSpend(UUID, BigDecimal)} correctly
     * decrements the accumulator by applying a negative increment to the Redis store.</p>
     *
     * <p>The test creates a {@link ValueOperations} mock, triggers the rollback operation,
     * and verifies that {@code increment} is invoked with {@code amount.negate().doubleValue()},
     * confirming that rollback uses a negative value rather than a separate decrement call.</p>
     *
     * @param cardId {@code UUID} identifying the card for which the rollback is performed.
     * @param amount {@code BigDecimal} the financial amount that should be rolled back.
     *
     * @see CardController
     * @see com.opayque.api.card.repository.VirtualCardRepository
     * @see CardTransactionService
     */
    @Property
    @Label("7. Rollback should increment by negative amount")
    void rollbackShouldDecrementAccumulator(
            @ForAll("validCardId") UUID cardId,
            @ForAll("financialAmounts") BigDecimal amount
    ) {
        TestContext ctx = setup();

        // Setup local ValueOperations mock
        ValueOperations<String, Object> valueOps = mock(ValueOperations.class);
        when(ctx.redisTemplate.opsForValue()).thenReturn(valueOps);

        ctx.service.rollbackSpend(cardId, amount);

        // Verify increment is called with NEGATIVE value
        verify(valueOps).increment(anyString(), eq(amount.negate().doubleValue()));
    }

    // =========================================================================
    // ARBITRARIES (DATA GENERATORS)
    // =========================================================================

    @Provide
    Arbitrary<UUID> validCardId() {
        return Arbitraries.create(UUID::randomUUID);
    }

    @Provide
    Arbitrary<BigDecimal> hugeAmounts() {
        return Arbitraries.bigDecimals()
                .between(BigDecimal.ZERO, new BigDecimal("999999999999.99"))
                .ofScale(2);
    }

    @Provide
    Arbitrary<BigDecimal> financialAmounts() {
        return Arbitraries.bigDecimals()
                .between(BigDecimal.ONE, new BigDecimal("10000.00"))
                .ofScale(2);
    }

    @Provide
    Arbitrary<BigDecimal> highPrecisionAmounts() {
        // Generate numbers like 10.123456789
        return Arbitraries.bigDecimals()
                .between(BigDecimal.ONE, new BigDecimal("1000.00"))
                .ofScale(10);
    }
}