package com.opayque.api.card.dto;

import com.opayque.api.card.entity.CardStatus;
import java.math.BigDecimal;
import java.util.UUID;

/**
 * Immutable Data-Transfer Object (DTO) returned to trusted clients after successful Virtual-Card
 * issuance within the oPayque Payment-Platform.
 *
 * <p>The payload is scoped under PCI-DSS Req-3.2: sensitive authentication data (PAN, CVV, Expiry)
 * are transmitted ONLY once over mutually-authenticated mTLS channels with perfect-forward-secrecy
 * (TLS 1.3, AES-256-GCM). Clients must not persist these values unless they are PCI-DSS Level-1
 * certified.
 *
 * <p>Field masking rules:
 *
 * <ul>
 *   <li>PAN – returned unmasked to the issuing client; last-4 is stored for support workflows
 *       (tokenized in transit via VTS for wallet provisioning).
 *   <li>CVV – single-use value, never stored post-delivery; HSM-generated with 10-minute TTL to
 *       mitigate replay.
 *   <li>Expiry – MM/YY format; aligned to ISO-8583 DE14 for downstream authorization routing.
 * </ul>
 *
 * <p>Monetary limits are expressed in the card's billing currency with {@link java.math.BigDecimal}
 * scale = 2 to prevent floating-point rounding artefacts. Monthly spend cap is enforced by the
 * Velocity-Engine before authorization is forwarded to the scheme.
 *
 * @param cardId Unique surrogate key generated by the card-vault; used for idempotency and token
 *     look-ups.
 * @param pan Primary-Account-Number (PAN) in plaintext; 16-19 digits, Luhn-validated, BIN-mapped to
 *     oPayque's program range.
 * @param cvv Card-Verification-Value; 3-digit for Visa/MC, 4-digit for Amex; cryptographically
 *     separated from PAN.
 * @param expiryDate Expiration in MM/YY format; co-validated with HSM to reject expired instruments
 *     at issuance time.
 * @param cardholderName Free-text embossed name; normalized to uppercase ASCII and filtered against
 *     OFAC/PEP lists.
 * @param currency ISO-4217 alphabetic code (e.g., "NGN") defining the billing currency for all
 *     subsequent ledger entries.
 * @param status Operational state governed by {@link CardStatus} lifecycle; transitions are audited
 *     in the tamper-evident card-event log.
 * @param monthlyLimit Spend ceiling reset on the 1st of each month at 00:00 UTC; enforced in
 *     real-time by the Velocity-Engine with 50 ms SLA.
 * @author Madavan Babu
 * @since 2026
 */
public record CardIssueResponse(
    UUID cardId,
    String pan, // 4111222233334444 (Unmasked)
    String cvv, // 123
    String expiryDate, // 12/29
    String cardholderName,
    String currency,
    CardStatus status,
    BigDecimal monthlyLimit
) {}