spring:
  profiles:
    active: dev # Default for local coding
  application:
    name: oPayque-API

# Custom properties
application:
  security:
    jwt:
      # Use a 64-character hex string in production! (REMEMBER TO CHANGE THIS!)
      secret-key: ${JWT_SECRET_KEY:v3ry-s3cr3t-b4nk-gr4d3-k3y-th4t-sh0uld-b3-v3ry-l0ng}
      expiration: 900000 # 15 mins
      refresh-token:
        expiration: 604800000 # 7 Days (milliseconds)