package com.opayque.api.admin.dto;

import com.opayque.api.admin.controller.AdminWalletController;
import com.opayque.api.admin.service.AdminWalletService;
import com.opayque.api.infrastructure.util.Masked;
import com.opayque.api.wallet.entity.Account;
import com.opayque.api.wallet.entity.AccountStatus;
import com.opayque.api.wallet.repository.AccountRepository;

import java.util.UUID;

/**
 * Represents the immutable response payload returned by the administrative
 * wallet APIs when querying a single {@link Account}.
 * <p>
 * This record aggregates the essential account attributes required by
 * back‑office operators while deliberately masking personally identifiable
 * information (PII) such as the {@code iban} and {@code ownerEmail}. The
 * {@link Masked} annotation applied to these fields triggers a custom JSON
 * serializer that redacts sensitive data before it leaves the service
 * boundary, thereby supporting compliance with data‑privacy regulations.
 * </p>
 *
 * <ul>
 *   <li>{@code id} – the globally unique {@link UUID} identifier of the
 *       {@link Account} entity (primary key, generated by the persistence layer).</li>
 *   <li>{@code iban} – the account’s International Bank Account Number, masked for
 *       security.</li>
 *   <li>{@code currency} – ISO‑4217 three‑letter currency code associated with
 *       the account.</li>
 *   <li>{@code status} – current lifecycle state of the account, represented by
 *       {@link AccountStatus}. This state drives the allowed administrative
 *       transitions defined in {@link AccountStatus#canTransitionTo}.</li>
 *   <li>{@code ownerEmail} – e‑mail address of the {@link com.opayque.api.identity.entity.User}
 *       owning the account, also masked.</li>
 * </ul>
 *
 * <p>
 * The static factory method {@link #fromEntity(Account)} provides a convenient
 * mapper from the JPA {@link Account} entity to this DTO, ensuring that only
 * the required view‑level data is exposed to API consumers.
 * </p>
 *
 * @see AdminWalletController
 * @see AdminWalletService
 * @see AccountRepository
 * @see MoneyDepositRequest
 * @see AdminDepositResponse
 *
 * @author Madavan Babu
 * @since 2026
 */
public record AdminAccountResponse(
        UUID id,
        @Masked
        String iban,
        String currency,
        AccountStatus status,
        @Masked
        String ownerEmail
) {
    // Static Mapper for convenience
    public static AdminAccountResponse fromEntity(Account account) {
        return new AdminAccountResponse(
                account.getId(),
                account.getIban(),
                account.getCurrencyCode(),
                account.getStatus(),
                account.getUser() != null ? account.getUser().getEmail() : null
        );
    }
}