{
 "title": "oPayque Banking API Dashboard",
 "description": "This is a custom essential only metrics dashboard made for monitoring oPayque Banking API Core operations using Prometheus Data source only for now. (Does not use Loki nor Tempo yet)",
 "tags": [
  "oPayque",
  "Prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Login Count",
   "type": "stat",
   "description": "Total User logins.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opayque_auth_login_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total JWT Generate Count",
   "type": "stat",
   "description": "Total number of JWT generated.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opayque_auth_jwt_generate_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Calculate Balance Method Counter",
   "type": "stat",
   "description": "This shows how many times calculate Balance repository method was called. (This is a core & critical operation)",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opayque_ledger_calculate_balance_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Currency Exchange Service Call Counter",
   "type": "stat",
   "description": "This denotes how many times the 3rd party ExchangeRate-API Service was called.",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opayque_exchange_api_latency_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Balance Aggregation Latency",
   "type": "stat",
   "description": "This shows how fast the API can calculate the running balances.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(opayque_ledger_calculate_balance_seconds_sum[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Uptime",
   "type": "timeseries",
   "description": "API Total runtime since deployment.",
   "gridPos": { "h": 21, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "process_uptime_seconds", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "JVM Heap Memory used in Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\", application=\"opayque-cloud-api\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Redis Token Blocklist Check Time (milliseconds)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opayque_auth_blocklist_check_seconds_max",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HikariCP (Total Connection Count)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hikaricp_connections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "API Request Queries",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 13, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_server_requests_seconds_count{application=\"opayque-cloud-api\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Free in Bytes",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "disk_free_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Logback Events Total (By Level)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "logback_events_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "API CPU Usage (Percent)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "{{job}}" }
   ]
  }
 ]
}